# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfoVUQe5mWvpaKGb1b7j8-b0ELR1r2SW
"""

import gradio as gr
import numpy as np
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

import tensorflow as tf
from tensorflow.keras.models import load_model
from PIL import Image

# Load model
model = load_model("fashionmnist.keras", compile=False)

label_names = [
    "T-shirt/Top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle Boot"
]

def predict_image(img):
    img = img.convert("L")
    img = img.resize((28, 28))
    img_array = np.array(img) / 255.0
    img_array = img_array.reshape(1, 28, 28, 1)

    predictions = model.predict(img_array)
    class_index = np.argmax(predictions)
    confidence = float(np.max(predictions))

    return {
        "Predicted Class": label_names[class_index],
        "Confidence": confidence
    }

iface = gr.Interface(
    fn=predict_image,
    inputs=gr.Image(type="pil"),
    outputs=gr.JSON(),
    title="FashionMNIST Classifier (CNN + RMSprop)",
    description="Upload gambar pakaian. Model dilatih menggunakan CNN dan optimizer RMSprop pada dataset FashionMNIST."
)

iface.launch()